[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0rc2"
update_changelog_on_bump = true
changelog_start_rev = "0.0.1"

tag_format = "$minor.$major.$patch$prerelease"

# While the project has not released stable version
major_version_zero = true
changelog_file = "CHANGELOG.md"

annotated_tag = true
version_files = [
    "paasify/version.py:__version__",
    "pyproject.toml:version"
]
