docs_dir: src/
site_dir: build/site/
site_name: "Paasify Documentation"

watch:
  - src
  - ../paasify

extra_css:
  - css/mkdocstrings.css

site_url: https://paasify.org/
nav:
    - Introduction: index.md
    - Documentation:
      - concepts.md
      - configuration.md
      - distribute.md
      - extend.md
      - advanced.md
    - Tutorial:
      - howto/learn_101.ipynb
    - Plugins:
      - Standard Library: apidoc/plugins/*
    - Reference:
      - Introduction: schema_doc/index.md
      - Configuration: schema_doc/schema_inject.md
      - Plugins: 
          - extend/extend_base.md
          - extend/extend_tags.md
      - Command line: usage.md
      - Python API:
        - schema_doc/python_app.md
        - schema_doc/python_project.md
        - schema_doc/python_api_other.md
    - About:
      - development.md
      - contribute.md
      - license.md

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/

plugins:
  - search
  - mkdocstrings
  #- schema_reader:
  #    include: 
  #      - "build/paasify_yml_schema.json"
  - mkdocs-jupyter


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details


theme:
    name: material
    locale: en
    features:
      - content.code.annotate

    #custom_dir: mkdocs_override/
    #custom_dir: overrides
    #custom_dir: custom_theme/
    palette: 

      # Palette toggle for light mode
      - scheme: default
        primary: light green
        accent: indigo
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        primary: blue grey
        accent: green light
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
