docs_dir: src/
site_dir: build/site/
site_name: "Paasify Documenation"

site_url: https://paasify.org/
nav:
    - introduction.md
    - Usage:
      - concepts.md
      - usage.md
      - schema_doc/schema_inject.md
      - advanced.md
    - Howto:
      - howto/learn_101.ipynb
    - API:
      - Introduction: schema_doc/index.md
      - Python:
        - schema_doc/python_app.md
        - schema_doc/python_project.md
      - Extend: 
        - extend/extend_apps.md
        - extend/extend_plugins.md

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/

plugins:
  - search
  - mkdocstrings
  #- schema_reader:
  #    include: 
  #      - "build/paasify_yml_schema.json"
  - mkdocs-jupyter


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
    name: material
    locale: en
    features:
      - content.code.annotate

    #custom_dir: mkdocs_override/
    #custom_dir: overrides
    #custom_dir: custom_theme/
    palette: 

      # Palette toggle for light mode
      - scheme: default
        primary: light green
        accent: indigo
        toggle:
          icon: material/brightness-7 
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        primary: blue grey
        accent: green light
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
