version: '3'

tasks:
  default:
    desc: Show all commands
    cmds:
      - task --list-all

  install:
    desc: Install jupyter dependencies
    cmds:
      - python -m bash_kernel.install

  build_doc:
    desc: Generate API doc
    deps: [install]
    run: once
    cmds:
      - ./gen_apidoc.sh
    sources:
      - ../paasify/*.py

  serve_jupyter:
    desc: Run jupyter playbook editor website
    interactive: true
    cmds:
      - jupyter-notebook --autoreload --notebook-dir src/jupyter/

  serve_doc:
    desc: Run mkdocs website
    deps: [build_doc]
    interactive: true
    cmds:
      - mkdocs serve

