name: "Bump release: stable"

env:
  python_version: "3.9"
  poetry_version: "1.2.1"


# # Old way
# on:
#   push:
#     branches:
#       - main
#     tags:
#       - '!**'
#     # tags-ignore:
#     #   - '[0-9]+.[0-9]+.[0-9]+'

# New way
on:

  workflow_dispatch:
    inputs:

      increment:
        description: 'Increment type: MAJOR, MINOR, PATCH or AUTO'
        default: "AUTO"
        type: choice
        options:
          - AUTO
          - MAJOR
          - MINOR
          - PATCH

      prerelease:
        description: 'Prerelease type: rc or stable for stable'
        default: "alpha"
        type: choice
        options:
          - rc
          - stable


jobs:

  install:
    
    strategy:
      fail-fast: false
    with:
      python_version: '3.9'
      poetry_version: '1.2.1'
    secrets:
      access_token: "${{ secrets.ACCESS_TOKEN }}"

    if: "github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'bump:')"
    uses: ./.github/workflows/_install.yaml

  bump_stable_version:
    needs: install
    runs-on: ubuntu-latest

    if: "github.ref == 'refs/heads/main' && !startsWith(github.event.head_commit.message, 'bump:')"
    steps:

      # Load project
      # ---------------------
      - name: Load cached python environment
        id: cached-env-install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: python_env--${{ runner.os }}--${{env.python_version}}--${{env.poetry_version}}

      - name: Fetch source code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
          fetch-depth: 0

      - name: Load cached venv
        id: cached-project-deps
        uses: actions/cache@v3
        with:
          path: ~/.venv
          key: venv--${{ runner.os }}--${{env.python_version}}--${{env.poetry_version}}--${{ hashFiles('**/poetry.lock') }}
        


      # Bump dist project
      # -----------------------------

      - id: release
        run: |2
          BRANCH=${GITHUB_REF_NAME}

          prerelease="${{github.event.inputs.prerelease}}"
          if [[ "${{github.event.inputs.prerelease}}" == 'stable' ]]; then
            prerelease=''
          fi

          increment="${{github.event.inputs.increment}}"
          if [[ "${{github.event.inputs.increment}}" == 'AUTO' ]]; then
            increment=''
          fi

          git log --oneline --abbrev-commit --graph --decorate --all --date-order --pretty=format:'%C(yellow)%h%Creset%C(auto)%d %Creset%s %C(dim)(%an, %ch)'

          # Because of: https://github.com/commitizen-tools/commitizen/issues/357
          rm CHANGELOG.md

          echo "prerelease=${prerelease}" >> "$GITHUB_OUTPUT"
          echo "increment=${increment}" >> "$GITHUB_OUTPUT"

      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: true
          prerelease: ${{steps.release.outputs.prerelease}}
          increment: ${{steps.release.outputs.increment}}

      - name: Print Version
        run: |
          source ~/.venv/bin/activate
          echo "Bumped to version ${{ steps.cz.outputs.version }}"
          echo "Project version: $(poetry version -s)"
          echo "Paasify version: $(paasify --version)"
